### ISSUE TITLE
Xcode 6.1.1 utsname() throws an error

### ISSUE THREAD

**Issue by ianhirschfeld** [dennisweissmann/Basics#1]
This line:
`var systemInfo = utsname()`
doesn't seem to work. I get the error:
`Missing argument for parameter 'sysname' in call`.

**Comment by dennisweissmann** [comment]
Thanks for catching that! Calling `utsname()` without parameters requires Swift 1.2 (included in Xcode 6.3 Beta). Please use the code of my [old SO answer](http://stackoverflow.com/revisions/26962452/1) and make sure you update the `DeviceList` with the one from my [current answer](http://stackoverflow.com/a/26962452/1489885).
