### ISSUE TITLE
iPad Air 2 detected instead of iPad Mini 4 for device code "iPad5,1"

### ISSUE THREAD

**Issue by ruipfcosta** [dennisweissmann/Basics#3]
I noticed the device code "iPad5,1" is being incorrectly used to identify iPad Air 2 when it should actually be detecting iPad Mini 4 (according to https://www.theiphonewiki.com/wiki/Models).
The issue seems to be on this section of the code:

```swift
case "iPad5,1", "iPad5,3", "iPad5,4":  self = iPadAir2
case "iPad5,1", "iPad5,2":             self = iPadMini4
```

**Comment by dennisweissmann** [comment]
Good catch! Thanks! 🙏 I've merged it :)
